## Python - A quick overview for scientists 

2018-04-19

Comprehensive Heart Failure Center, University Clinic Würzburg

by Konrad U. Förstner <konrad.foerstner@uni-wuerzburg.de>

https://github.com/konrad/2018-04-19-A_short_Python_overview_for_scientists

<img src="qrcode.png" alt="Drawing" style="width: 200px"/>

## Intro

### Fastest growing language (in data science and in general)

* [stackoverflow Blog - The Incredible Growth of Python](https://stackoverflow.blog/2017/09/06/incredible-growth-python/)
* [stackoverflow Blog - Why is Python Growing So Quickly?](https://stackoverflow.blog/2017/09/14/python-growing-quickly/) (spoiler: pandas)

### Widely used in tech industry and scientific instistutions

* [8 World-Class Software Companies That Use Python](https://realpython.com/world-class-companies-using-python/)
* [https://www.python.org/about/success/#scientific](Python Success Stories)
    * e.g. [NASA](https://www.python.org/about/success/usa/), [CERN](https://cds.cern.ch/record/2274794)

### THE language for data science (besides R)

### The Zen of Python

### A lot of syntactic sugar

### Readability

### Multiple programming paradigms

In [ ]:
# procedual

In [ ]:
# object oriented

In [3]:
# functional

### Batteries included ...

### ... and countless third party libraries

### How to work with Python

- REPL (python / ipython)
- Python scripts
- Jupyter Notebooks / Jupyter Lab

### Great community

Search for video on youtube:

* [PyCon](https://www.youtube.com/results?search_query=PyCon&search_type=)
* [SciPy](https://www.youtube.com/results?search_query=SciPy&search_type=)
* [EuroSciPy](https://www.youtube.com/results?search_query=EuroPy&search_type=)
* ... many more

### Language development by the community - PEPs

* [Python Enhancement Proposals](https://www.python.org/dev/peps/)

## Live Demo

### Numpy

In [25]:
import numpy as np
a = np.random.random((2,2))
b = np.random.random((2,2))
print(a)
print(b)
print(a/b*100)

[[0.65906669 0.13219767]
 [0.3005538  0.1705903 ]]
[[0.92772379 0.32723062]
 [0.01570006 0.07185244]]
[[  71.04126142   40.39893208]
 [1914.34803345  237.41754058]]


### SciPy

### pandas

### scikit-learn

### matplotlib

### seaborn

### bokeh

## How to start?

Install [Anaconda](https://www.anaconda.com/download/#linux) that bring Python plus numerous scientific packages.
